package templates

const ServiceTemplate = `// Code generated by pengu-lang compiler. DO NOT EDIT.
package main

import (
	{{if .HasJson}}"encoding/json"{{end}}
	"fmt"
	"log"
	"net/http"
	{{if .HasAuth}}"strings"{{end}}
)

// Define structs specified by "parse json" actions
{{range .Routes}}
	{{range .Actions}}
		{{if eq .Type "parse_json"}}
type {{index .Args 0}} map[string]interface{}
		{{end}}
	{{end}}
{{end}}

func main() {
	mux := http.NewServeMux()

{{if .HealthEnabled}}
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, "healthy")
	})
{{end}}

{{if .MetricsEnabled}}
	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprint(w, "metrics_ok")
	})
{{end}}

{{range .Routes}}
	mux.HandleFunc("{{.Path}}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != "{{.Method}}" {
			http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
			return
		}

		{{range .Actions}}
			{{if eq .Type "log"}}
		log.Println("{{index .Args 0}}")

			{{else if eq .Type "respond"}}
		w.WriteHeader({{index .Args 0}})
		fmt.Fprint(w, "{{index .Args 1}}")

			{{else if eq .Type "parse_json"}}
		var reqPayload {{index .Args 0}}
		if err := json.NewDecoder(r.Body).Decode(&reqPayload); err != nil {
			http.Error(w, "Bad Request: failed to parse JSON", http.StatusBadRequest)
			return
		}

			{{else if eq .Type "auth"}}
		authHeader := r.Header.Get("Authorization")
		if !strings.HasPrefix(authHeader, "Bearer ") {
			http.Error(w, "Unauthorized: missing {{index .Args 0}} token", http.StatusUnauthorized)
			return
		}
			{{end}}
		{{end}}
	})
{{end}}

	var handler http.Handler = mux

{{range .Middleware}}
	{{if eq . "logging"}}
	handler = loggingMiddleware(handler)
	{{else if eq . "auth jwt"}}
	handler = jwtMiddleware(handler)
	{{end}}
{{end}}

	fmt.Println("Starting service '{{.Name}}' (v{{.Version}}) on :8080...")
	log.Fatal(http.ListenAndServe(":8080", handler))
}

// Middleware Implementations
func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Printf("Incoming %s request to %s", r.Method, r.URL.Path)
		next.ServeHTTP(w, r)
	})
}

func jwtMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Mock JWT Validation
		if auth := r.Header.Get("Authorization"); auth == "" {
			http.Error(w, "Forbidden: Invalid JWT", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}
`
