package templates

const ServiceTemplate = `// Code generated by pengu-lang compiler. DO NOT EDIT.
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	fmt.Println("Starting service '{{.Name}}' (v{{.Version}}) on :8080...")

{{range .Routes}}
	http.HandleFunc("{{.Path}}", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != "{{.Method}}" {
			http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
			return
		}

		{{range .Actions}}
			{{if eq .Type "log"}}
		log.Println("{{index .Args 0}}")
			{{else if eq .Type "respond"}}
		w.WriteHeader({{index .Args 0}})
		fmt.Fprint(w, "{{index .Args 1}}")
			{{end}}
		{{end}}
	})
{{end}}

	log.Fatal(http.ListenAndServe(":8080", nil))
}
`
